### ISSUE TITLE
shift clicking out of hammer crafter caused crash

### ISSUE THREAD

**Issue by SDUBZ** [thebrightspark/SparksHammers#10]
forge:1.11.2-2201
sparks hammer:1.11-1.4.4.1
crash report:
[crash-2017-01-02_12.32.05-client.txt](https://github.com/thebrightspark/SparksHammers/files/680300/crash-2017-01-02_12.32.05-client.txt)

**Comment by thebrightspark** [comment]
Well for starters, you're using MC 1.11.2 with my mod which is built for 1.11 (and I haven't started building for that version yet), so I can't do much about it at the moment. However I have tested this within my development environment for the latest version (MC 1.11) on a client and server world, and I had no issues.

I also tested using the versions you stated, and still had no issues (only tested on a client world).

Tell me exactly what you did and what you crafted. Also if it happens on a client or server world.
I can't guarantee I'll fix it anyway, due to the difference in MC versions.

**Comment by SDUBZ** [comment]
crafted a stone hammer and shift clicked out the excess cobble out of the head part of the hammer crafter and it crashed me back to desktop,also can you test while having inventory tweaks thinking it may be a conflict of some kind

**Comment by thebrightspark** [comment]
Ahh thanks, found the issue. I was using a null ItemStack still when ItemStacks can't be null anymore.

This will be fixed in the next version.
Fixed in commit https://github.com/thebrightspark/SparksHammers/commit/f85e4691ebf4670a249b12646576811d19ca0ac4
