### ISSUE TITLE
Crash when looking at Usage in JEI

### ISSUE THREAD

**Issue by drakray** [thebrightspark/SparksHammers#15]
http://pastebin.com/3FZtfqkw
Crashed when trying to go on Anvil in JEI for Wooden Excavator, may crash with others

**Comment by drakray** [comment]
found out that the crash is caused by Anvil recipe, not JEI itself, as trying to put a Hammer/Excavator to enchant with an enchanting book [crash](http://pastebin.com/Mi9pzKG3)

**Comment by thebrightspark** [comment]
I've had a look and I can't see how that's caused by my mod. Testing what you said doesn't cause any issue with just my mod, so I think you might have a core mod or something changing something in the ToolMaterial class, or something from another mod is causing the issue somehow. Maybe they're setting a repair material as null when ItemStacks can't be null anymore?

But yeah, I don't think this is an issue with my mod. I don't set repair materials for my tools.

**Comment by drakray** [comment]
I think I found the culprit in D3Core, [will ask](https://github.com/DoubleDoorDevelopment/D3Core/issues/21) them to take a look
