### ISSUE TITLE
Are you open to pull requests?

### ISSUE THREAD

**Issue by maxhenkes** [thebrightspark/SparksHammers#3]
Heya man. We've been using your mod in our pack for quite a while but sadly the botania tools are pretty dang useless because they don't repair themselves with mana. I've forked your mod locally and have implemented mana repair the same way botania does it for it's tool. Are you working on something similar or would you be open to a pull request? (Which I still have to figure out, never contributed to other projects before)

**Comment by thebrightspark** [comment]
Ah great to hear!
I've not worked on this mod for a little while... Mainly because I got stuck into trying to make a tech mod, and then a tech add-on, and sorta lost interest in going through my to-do for this one XD
I had plans to add the Botania integration properly but never got round to it! With a little push from user like you I'll get back on it soon :P

I'd be happy for you to create a pull request. It'll give me a good starting point and I'd be very grateful. I've never really used pull request much either, so unfortunately I can't help too much. It's either on this repository or your forked repository you have to click "pull request" and go from there, making sure you're asking to pull it into the correct branch as well, which currently is my 1.10 branch.

**Comment by maxhenkes** [comment]
Dangit I didn't realize 1.10 was BEHIND master. Derp :D 

Oh well, I was wondering why the Mjolnir texture was broken... Doesn't matter, I'm gonna see if I can get this pull request to work in a few mins :D

EDIT: nvm I can't read version numbers apparently ._.

**Comment by thebrightspark** [comment]
Wrong way around, 1.10 is ahead of the master ;D

Alright cool, thanks!

**Comment by maxhenkes** [comment]
Okay making a pull request was rather easy, it's up now :)

**Comment by thebrightspark** [comment]
Thanks I see it. I'll take a closer look at it later (I'm out atm). I might make a couple of adjustments to the way you've setup the registration (sorry I'm picky about how I lay it out) but other than that it looks good :D

Thanks a lot for your help and input!

**Comment by maxhenkes** [comment]
Yeah no worries :P I wasn't exactly sure how you wanted it so I did a minimal edit so I could test if it ran WITHOUT Botania :P And leave however you want to organize that up to you :)

Always happy to help! :)

**Comment by thebrightspark** [comment]
Yes, that's brilliant :)

**Comment by maxhenkes** [comment]
Also, since this was mostly done because enough people on my server constantly complained about mana hammers being useless, I might work on adding the void ability from the Elementium tools as another pull request someday... If enough players complain :P Unless you have plans for that :D

**Comment by thebrightspark** [comment]
This'll be coming in the next update soon, so I'll close this. Thanks a lot :)
If you have any questions or anything, feel free to message me on Curse.

**Comment by maxhenkes** [comment]
@thebrightspark If you have the time give me a nudge here/curse when you put up the new version so I can add it to my pack :)

**Comment by thebrightspark** [comment]
@iPencil Just updated the mod! Enjoy!
