### ISSUE TITLE
[CTD] On breaking custom Excavator

### ISSUE THREAD

**Issue by drakray** [thebrightspark/SparksHammers#31]
Crash: https://pastebin.com/gtJqjpjU
CustomTool.json: https://pastebin.com/8GP1p3bg

MC 1.11.2
Forge 2315
SH 1.6.5

itemFlint add to oreDict via CraftTweaker

Crash occured when mining dirt with Flint Excavator

**Comment by thebrightspark** [comment]
Thanks, looks like it's something that I missed when porting to 1.11, and it's a simple fix. I'll get that fixed soon.

Just gonna leave the reference to the issue here for me for later:
https://github.com/thebrightspark/SparksHammers/blob/1.12/src/main/java/brightspark/sparkshammers/util/CommonUtils.java#L238

**Comment by thebrightspark** [comment]
Sorry, forgot to reply back to this issue. I should hopefully have fixed the issue in commmit https://github.com/thebrightspark/SparksHammers/commit/c72c967429fff1d7672839db65687152ff202647

Please post back here if you still get the same error on the next update.
