### ISSUE TITLE
Ur latest version still crashes

### ISSUE THREAD

**Issue by maxhenkes** [thebrightspark/SparksHammers#6]
So I see you've rewritten the registering for mana tools and I believe you misunderstood the original intention:

> thebrightspark commented 8 days ago
> Thanks I see it. I'll take a closer look at it later (I'm out atm). **I might make a couple of adjustments to the way you've setup the registration (sorry I'm picky about how I lay it out)** but other than that it looks good :D

See the reason I registered them in a separate class is because now you are having exactly the issue I fixed: 
(In ShModItems)

```
package com.brightspark.sparkshammers.init;

import com.brightspark.sparkshammers.item.ItemAOE;
import com.brightspark.sparkshammers.item.ItemHammerMana;
import com.brightspark.sparkshammers.reference.Names;
import com.brightspark.sparkshammers.util.LoaderHelper;

public class SHModItems
{
```

specifically import com.brightspark.sparkshammers.item.ItemHammerMana;

regardless of you not using the class later on with you checking if Botania is installed, you are still importing a class that does not exist, and therefore it crashes:

http://pastebin.com/uaxSSTgE

You should register them in a separate class similar to how I did it in the pull request, then you only import ItemHammerMana when you actually have it available!

**Comment by thebrightspark** [comment]
Ah yes... how could I have been so stupid. Sorry about that!
Thanks again, I've fixed it and a patch will be up soon.

**Comment by maxhenkes** [comment]
@thebrightspark  Don't worry :P I don't actually have the crashing issue, I've just noticed the update and thought "wait what" :P 

I've actually got another issue about nbt tags when breaking stuff with the hammers, but it also happens to other stuff like botania shatterer.

I'm not entirely sure if it's your mods fault, but I'd like to talk about a potential fix (not sure how much work you wanna put into this mod). You don't happen to have something like discord for easier text chat? Kind of a complicated issue but I can lay it out on github too if you prefer!

**Comment by thebrightspark** [comment]
Well you were right to think that :)

Well I know from fiddling with NBT for blocks in mods that I have unreleased, that NBT will only save to the dropped item if you save it yourself. So if you're question is "why isn't this machine saving it's power when broken?" or similar, then it's probably because the developer didn't make the block copy its NBT data to the item stack within the item entity when the block is broken.

I do have Discord, although I think you can only pm someone that's in a server you're also on? You can also write it out here in a new issue or pm me on [CurseForge](https://minecraft.curseforge.com/projects/sparks-hammers) - either way I'll respond as soon as I can :)

**Comment by maxhenkes** [comment]
You can add them in discord and chat, I've added a bunch of people from reddit and github that way :)

You can try adding me in discord, name is "CreeperShift#5788"

**Comment by maxhenkes** [comment]
Woops forgot you also need the # stuff for the name :P
